stages:
  - build-frontend
  - test-frontend
  - build-backend
  - test-backend
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: test

build-frontend:
  stage: build-frontend
  image: node:latest
  script:
    - cd Frontend/ecom
    - npm ci
    - npm run build
  artifacts:
    paths:
      - Frontend/ecom/dist
  cache:
    paths:
      - Frontend/ecom/node_modules

test-frontend:
  stage: test-frontend
  image: cypress/base:12.8.1
  script:
    - cd Frontend/ecom
    - npm ci
    - npm run test:e2e:ci
  artifacts:
    when: always
    paths:
      - Frontend/ecom/cypress/videos
      - Frontend/ecom/cypress/screenshots
  cache:
    paths:
      - Frontend/ecom/node_modules

build-backend:
  stage: build-backend
  image: maven:latest
  script:
    - cd Backend/ECOMBack
    - mvn clean package
  artifacts:
    paths:
      - Backend/ECOMBack/target/*.jar
  cache:
    paths:
      - Backend/ECOMBack/.m2

test-backend:
  stage: test-backend
  image: maven:latest
  script:
    - cd Backend/ECOMBack
    - mvn test
  cache:
    paths:
      - Backend/ECOMBack/.m2

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploy your app using your preferred method"
  environment:
    name: production
  when: manual
  only:
    - main
