stages:
  - build-frontend
  - build-backend
  - test
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: karo
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_DATASOURCE_URL: ${url}
  SPRING_DATASOURCE_USERNAME: ${username}
  SPRING_DATASOURCE_PASSWORD: ${password}
  SPRING_JPA_PROPERTIES_JAKARTA_PERSISTENCE_SHAREDCACHE_MODE: ENABLE_SELECTIVE
  SERVER_PORT: 9090
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ERROR
  LOGGING_LEVEL_COM_PACKETPUB_RESTAPP: INFO
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
  

build-frontend:
  stage: build-frontend
  image: node:latest
  script:
    - cd Frontend/ecom
    - npm ci
    - npm run build
  artifacts:
    paths:
      - Frontend/ecom/dist
  cache:
    paths:
      - Frontend/ecom/node_modules

build-backend:
  stage: build-backend
  image: maven:latest
  script:
    - cd Backend/ECOMBack
    - mvn clean package
  artifacts:
    paths:
      - Backend/ECOMBack/target/*.jar
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - Backend/ECOMBack/.m2/repository

test:
  stage: test
  image: openjdk:11
  services:
    - name: openjdk:11
      alias: backend
  script:
    - cd Backend/ECOMBack
    - java -jar target/*.jar &
    - sleep 30
    - cd ../../Frontend/ecom
    - docker run -v $PWD:/e2e -w /e2e cypress/base:12.8.1 /bin/bash -c "npm ci && npm run test:e2e:ci"
  artifacts:
    when: always
    paths:
      - Frontend/ecom/cypress/videos
      - Frontend/ecom/cypress/screenshots
  cache:
    paths:
      - Frontend/ecom/node_modules
      - Backend/ECOMBack/.m2

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploy your app using your preferred method"
  environment:
    name: production
  when: manual
  only:
    - main
