stages:
  - build
  - test
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: test

.build_template: &build_definition
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - Frontend/ecom/node_modules
      - Backend/ECOMBack/.m2/repository

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd Frontend/ecom
    - npm ci
    - npm run build
  artifacts:
    paths:
      - Frontend/ecom/dist
  <<: *build_definition

build-backend:
  stage: build
  image: maven:latest
  script:
    - cd Backend/ECOMBack
    - mvn clean package
  artifacts:
    paths:
      - Backend/ECOMBack/target/*.jar
  <<: *build_definition

test:
  stage: test
  image: node:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - cd Backend/ECOMBack
    - docker run -d -p 9090:9090 --name backend openjdk:11 java -jar target/*.jar
    - cd ../../Frontend/ecom
    - npm ci
    - npm run serve &
    - sleep 30
    - npm run test:e2e:ci
  artifacts:
    when: always
    paths:
      - Frontend/ecom/cypress/videos
      - Frontend/ecom/cypress/screenshots
  <<: *build_definition

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploy your app using your preferred method"
  environment:
    name: production
  when: manual
  only:
    - main
