
#New Pipeline
stages:
  - build-frontend
  - test-frontend
  - build-backend
  - test-backend
  - deploy

build-frontend:
  stage: build-frontend
  image: node:latest
  script:
    - cd Frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - Frontend/dist
  cache:
    paths:
      - Frontend/node_modules

test-frontend:
  stage: test-frontend
  image: cypress/base:latest
  script:
    - cd Frontend
    - npm ci
    - npx cypress run
  artifacts:
    when: always
    paths:
      - Frontend/cypress/videos
      - Frontend/cypress/screenshots
  cache:
    paths:
      - Frontend/node_modules

build-backend:
  stage: build-backend
  image: maven:latest
  script:
    - cd Backend
    - mvn clean install
  artifacts:
    paths:
      - Backend/target/*.jar
  cache:
    paths:
      - Backend/.m2

test-backend:
  stage: test-backend
  image: maven:latest
  script:
    - cd Backend
    - mvn test
  cache:
    paths:
      - Backend/.m2

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploy your app using your preferred method"
  environment:
    name: production
  when: manual
  only:
    - main